import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Next_App_Template</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div>Hello</div>
        </div>
    );
};
Home.displayName = 'Home';

export default Home;
